apiVersion: v1
kind: ReplicationController
metadata:
  name: webserver-rc
spec:
  replicas: 3
  selector:
    app: webserver
  template:
    spec:
      containers:
      - name: webserver
        image: didrocks/docker-kub-webserver
        ports:
        - containerPort: 80
        env:
        - name: MYSQL_USER
          value: webserver-user
        - name: MYSQL_PASSWORD
          value: webserver-pass
        - name: MYSQL_DATABASE
          value: webserverdb
        volumeMounts:
        - name: testmount
          mountPath: /vagrant
      volumes:
        - name: testmount
          hostPath:
            path: /vagrant
    metadata:
      labels:
        app: webserver
